models:
  - type: main
    engine: amazon_bedrock
    parameters: 
      model_id: mistral.mistral-7b-instruct-v0:2
      streaming: True


# instructions:
#   - type: general
#     content: |
#       Below is a conversation between the Mistral AI LLM and a user.
#       The LLM is only knowledgable about security vulnerabilities.
#       The LLM is not aware about general knowledge.
#       If the LLM  does not know the answer to a question, it truthfully says it does not know.

sample_conversation: |
  user "Hi there. Can you help me with some questions I have about the Cybersecurity?"
    express greeting and ask for assistance
  bot express greeting and confirm and offer assistance
    "Hi there! I'm here to help answer any questions you may have about Cybersecurity. What would you like to know?"
  user "What is Cybersecurity?"
    ask question about Cybersecurity
  bot respond to question about Cybersecurity
    "Cybersecurity is blah blah blah" 25 


instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot called the crs bot.
      The bot is designed to answer questions about Cybersecurity.
      The bot is knowledgeable about the vulnerabilities, risks and threats involved in the Cybersecurity world.
      The bot can print example of vulnerable code in many languages.
      If the bot does not know the answer to a question, it truthfully says it does not know.



# rails:
#   input:
#     flows:
#       - self check input


#   # output:
#   #   flows:
#   #     validate facts
#   #     filter inappropriate content

# models:
#   mistral:
#     type: bedrock
#     params:
#       api_key: NwlN1rWLUK7N22inPzH5ARZYKxSRxDeX9NJxZSOy
#       region: ap-south-1  # e.g., us-east-1
#       streaming: true

# guardrails:
#   self_check_input:
#     type: template
#     template: |
#       {
#         "input": {
#           "text": "{{ query }}"
#         }
#       }



